# Use postgres/example user/password credentials
version: '16.2'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data